### ISSUE TITLE
Survey 

### ISSUE THREAD

**Issue by johnwfaulk** [TIY-Columbia-Front-End-Engineering/assignments-feb-2016#6]
https://github.com/johnwfaulk/Survey

**Comment by ericmcdaniel** [comment]
Be sure to edit your original description to include the link to your repository.

**Comment by ericmcdaniel** [comment]
Good work. Here's a few points of feedback:

* Your form's `action` points to the wrong address. It should be `localhost:3000` not `localhost:3000.com`
* HTML `ids` are one word only. You can't have an `id` or `class` that contains spaces.
    - The reason your labels are working is because they look for the element to highlight via the first word in their `for` attribute. In [this example](https://github.com/johnwfaulk/Survey/blob/master/index.html#L12), your `label` uses the word `First` (but not `name`). You then have an input with the `id` `First name`, which technically contains the `id` `First`, so it is highlighted correctly. We can discuss this in more detail over slack or on Monday.
* Likewise, [the `name` attribute should not contain spaces](https://github.com/johnwfaulk/Survey/blob/master/index.html#L92)
* Good job researching the `disabled` and `selected` attributes.
* [Your form is not submitting properly](https://github.com/johnwfaulk/Survey/blob/master/index.html#L126). You should use the `<input type="submit">` instead of `button`.
* [Your CSS rule-set](https://github.com/johnwfaulk/Survey/blob/master/src/css/index.css#L1) is not working as anticipated because you are actually targeting `name` elements within `#First`, not an element with the `id` `First name`. Remember, ids and classes can't contain spaces.
