### ISSUE TITLE
Survey

### ISSUE THREAD

**Issue by DrewSancho** [TIY-Columbia-Front-End-Engineering/assignments-feb-2016#8]
https://github.com/DrewSancho/survey

**Comment by DrewSancho** [comment]
Second offence

**Comment by ericmcdaniel** [comment]
Think about the task that states "Briefly describe why you found the movie enjoyable." What about your input would provide a bad experience for users who want to enter more than a few words?

Use `labels` instead of plain text to give titles to each of your `inputs`. Remember, the `for` attribute on the `label` targets the `id` attribute on an input.

**Comment by DrewSancho** [comment]
addressed the issues your brought up and completed them as such please forgive my crappy coding skills.

**Comment by ericmcdaniel** [comment]
Good work! A few points of feedback:

* `<textarea>` is a better element to use for questions that a user could provide detail longer than a few words.
* You have some indentation issues throughout: [1](https://github.com/DrewSancho/survey/blob/master/index.html#L31-L38), [2](https://github.com/DrewSancho/survey/blob/master/index.html#L130-L134), [3](https://github.com/DrewSancho/survey/blob/master/index.html#L146-L147).
* [comic is not a font](https://github.com/DrewSancho/survey/blob/master/src/css/index.css#L12)
